config/routes.rb
Rails.application.routes.draw do
  resources :departments
  resources :offices
  resources :offices
  resources :offices
  devise_for :staffs

  resources :projects
  resources :offices
  resources :skillsets
  resources :tools
  resources :staffs

  authenticated :user do
    root 'skillsets#index', as: :authenticated_root
  end
  root 'welcome#index'

end

app/models/staff.rb
class Staff < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :skillsets
	has_many :tools, :through => :skillsets
	belongs_to :office
	belongs_to :department
	has_and_belongs_to_many :projects

	def name_full
		name = name_first + ' ' + name_last
	end

	def tenure
	  now = Time.now.utc.to_date
	  now.year - start.year - (start.to_date.change(:year => now.year) > now ? 1 : 0)
	end

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_staff!, except: [:index, :show]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all.order('name_first')
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
    @staff = Staff.find(params[:id])
    @skillset = Skillset.find(params[:id])
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
    @projects = Project.all
  end

  # GET /staffs/1/edit
  def edit
    @projects = Project.all
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name_first, :name_last, :department_id, :office_id, :title, :bio, :start, :project_ids => [])
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@staff.errors.count, 'error') %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :office_id %>
    <%= f.collection_select :office_id, Office.all, :id, :location, {prompt: true}, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :department_id %>
    <%= f.collection_select :department_id, Department.all, :id, :name, {prompt: true}, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :bio %>
    <%= f.text_area :bio, autofocus: true, class: 'form-control' %>
  </div>
  <div class='form-inline'>
    <%= f.label :start %>
    <%= f.date_select :start, {:start_year => 1970, :discard_day => true}, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :projects %>
    <%= f.collection_check_boxes :project_ids, Project.all, :id, :name, class: 'form-control' %>
  </div>

  <table class='table table-striped'>
    <thead>
      <tr>
        <th></th>
        <th>Project</th>
        <th>Description</th>
      </tr>
    </thead>

    <tbody>
      <%= f.collection_check_boxes(:project_ids, Project.all, :id, :name) do |b| %>
        <%= b.label(class: 'check_box') do %>
          <tr>
            <td><%= b.check_box(class: 'check_box') %></td>
            <td><%= b.object.name %></td>
            <td><%= b.object.description %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <div class='form-group'>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form' %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<h1>
  All Staff <span class='badge'><%= @staffs.count %></span>
</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Department</th>
      <th>Title</th>
      <th>Office</th>
      <th colspan='3'></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= link_to staff.name_first, staff %></td>
        <td><%= link_to staff.name_last, staff %></td>
        <td><%= link_to staff.department.name, department_path(staff.department_id) %></td>
        <td><%= staff.title %></td>
        <td><%= link_to staff.office.location, office_path(staff.office_id) %></td>
        <% if current_staff %>
          <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
          <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Staff', new_staff_path %>

app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form' %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<h1><%= @staff.name_full %></h1>

<p>
  <strong>Office:</strong>
  <%= link_to @staff.office.location, office_path(@staff.office_id) %>
</p>
<p>
  <strong>Title:</strong>
  <%= @staff.title %>
</p>
<p>
  <strong>Bio:</strong>
  <%= @staff.bio %>
</p>
<p>
  <strong>Tenure:</strong>
  <% unless @staff.start.nil? || @staff.start == 0 %>
    <%= @staff.tenure %>+ years
  <% end %>
</p>

<div class='row'>
  <div class='col-md-6'>
    <div class='panel panel-default'>
      <!-- Default panel contents -->
      <div class='panel-heading'>
        <h4>Projects</h4>
      </div>

      <!-- Table -->
      <table class='table table-hover'>
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
          </tr>
        </thead>

        <tbody>
          <% @staff.projects.each do |project| %>
            <tr>
              <td><%= link_to project.name, project_path %></td>
              <td><%= project.description %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class='col-md-6'>
    <div class='panel panel-default'>
      <!-- Default panel contents -->
      <div class='panel-heading'>
        <h4>Skillsets</h4>
      </div>

        <!-- Table -->
        <table class='table table-hover'>
          <thead>
            <tr>
            <th>Skill <%= link_to '(New Skillset)', new_skillset_path %></th>
            <th>Proficiency</th>
          </tr>
        </thead>

        <tbody>
          <% @staff.tools.each do |tool| %>
            <tr>
              <td><%= link_to tool.name, tool_path %></td>
              <td><%= @skillset.proficiency %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<% if current_staff %>
  <%= link_to 'Edit', edit_staff_path(@staff) %> |
<% end %>

<%= link_to 'All Staff', staffs_path %>