config/routes.rb
Rails.application.routes.draw do
  resources :departments
  resources :offices
  resources :offices
  resources :offices
  devise_for :staffs

  resources :projects
  resources :offices
  resources :skillsets
  resources :tools
  resources :staffs

  authenticated :user do
    root 'skillsets#index', as: :authenticated_root
  end
  root 'welcome#index'

end

app/models/office.rb
class Office < ActiveRecord::Base
  has_many :staffs
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_staff!, except: [:index, :show]

  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.all.order('location')
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: 'Office was successfully created.' }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, notice: 'Office was successfully updated.' }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: 'Office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.require(:office).permit(:location)
    end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.erb
<%= form_for(@office) do |f| %>
  <% if @office.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@office.errors.count, 'error') %> prohibited this office from being saved:</h2>

      <ul>
      <% @office.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :location %>
    <%= f.text_field :location, autofocus: true, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :street %>
    <%= f.text_field :street, autofocus: true, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :city %>
    <%= f.text_field :city, autofocus: true, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :state %>
    <%= f.text_field :state, autofocus: true, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :zip %>
    <%= f.text_field :zip, autofocus: true, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :remote %>
    <%= f.check_box :remote, autofocus: true, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/offices/edit.html.erb
<h1>Editing Office</h1>

<%= render 'form' %>

<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

app/views/offices/index.html.erb
<h1>All Offices</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>
        Location
        <small class="text-muted"><i class='fa fa-location-arrow'> Satellite Office</i></small>
      </th>
      <th>Staff</th>
      <th colspan='3'></th>
    </tr>
  </thead>

  <tbody>
    <% @offices.each do |office| %>
      <tr>
        <td>
          <%= link_to office.location, office %>
          <% if office.remote == true %>
            <i class='fa fa-location-arrow'></i>
          <% end %>
        </td>
        <td><span class='badge'><%= office.staffs.count %></span></td>
        <td><%= link_to 'Show', office %></td>
        <td><%= link_to 'Edit', edit_office_path(office) %></td>
        <td><%= link_to 'Destroy', office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Office', new_office_path %>

app/views/offices/new.html.erb
<h1>New Office</h1>

<%= render 'form' %>

<%= link_to 'Back', offices_path %>

app/views/offices/show.html.erb
<p>
  <strong>Location:</strong>
  <%= @office.location %>
</p>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Staff</th>
      <th>Title</th>
      <th>Department</th>
    </tr>
  </thead>

  <tbody>
    <% @office.staffs.each do |staff| %>
      <tr>
        <td><%= link_to staff.name_full, staff %></td>
        <td><%= staff.title %></td>
        <td><%= link_to staff.department.name, department_path(staff.department_id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_office_path(@office) %> |
<%= link_to 'Back', offices_path %>