config/routes.rb
Rails.application.routes.draw do
  resources :departments
  resources :offices
  resources :offices
  resources :offices
  devise_for :staffs

  resources :projects
  resources :offices
  resources :skillsets
  resources :tools
  resources :staffs

  authenticated :user do
    root 'skillsets#index', as: :authenticated_root
  end
  root 'welcome#index'

end

app/models/skillset.rb
class Skillset < ActiveRecord::Base
	belongs_to :staff
	belongs_to :tool
end

app/controllers/skillsets_controller.rb
class SkillsetsController < ApplicationController
  before_action :set_skillset, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_staff!, except: [:index, :show]

  # GET /skillsets
  # GET /skillsets.json
  def index
    @skillsets = Skillset.all
  end

  # GET /skillsets/1
  # GET /skillsets/1.json
  def show
  end

  # GET /skillsets/new
  def new
    @skillset = current_staff.skillsets.build
    @tools = Tool.all
  end

  # GET /skillsets/1/edit
  def edit
  end

  # POST /skillsets
  # POST /skillsets.json
  def create
    @skillset = current_staff.skillsets.build(skillset_params)

    respond_to do |format|
      if @skillset.save
        format.html { redirect_to @skillset, notice: 'Skillset was successfully created.' }
        format.json { render :show, status: :created, location: @skillset }
      else
        format.html { render :new }
        format.json { render json: @skillset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skillsets/1
  # PATCH/PUT /skillsets/1.json
  def update
    respond_to do |format|
      if @skillset.update(skillset_params)
        format.html { redirect_to @skillset, notice: 'Skillset was successfully updated.' }
        format.json { render :show, status: :ok, location: @skillset }
      else
        format.html { render :edit }
        format.json { render json: @skillset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skillsets/1
  # DELETE /skillsets/1.json
  def destroy
    @skillset.destroy
    respond_to do |format|
      format.html { redirect_to skillsets_url, notice: 'Skillset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skillset
      @skillset = Skillset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skillset_params
      params.require(:skillset).permit(:staff_id, :tool_id, :proficiency)
    end
end

app/helpers/skillsets_helper.rb
module SkillsetsHelper
end

app/views/skillsets/_form.html.erb
<%= form_for(@skillset) do |f| %>
  <% if @skillset.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@skillset.errors.count, 'error') %> prohibited this skillset from being saved:</h2>

      <ul>
      <% @skillset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :tool_id %>
    <%= f.collection_select :tool_id, Tool.all.collect, :id, :name, {prompt: true}, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :proficiency %>
    <%= f.select :proficiency, [['Novice'], ['Competent'], ['Experienced'], ['Expert']], {prompt: true}, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/skillsets/edit.html.erb
<h1>Editing Skillset</h1>

<%= render 'form' %>

<%= link_to 'Show', @skillset %> |
<%= link_to 'Back', skillsets_path %>

app/views/skillsets/index.html.erb
<h1>Listing Skillsets</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Staff</th>
      <th>Tool</th>
      <th>Proficiency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skillsets.each do |skillset| %>
      <tr>
        <td><%= skillset.staff.name_full if skillset.staff %></td>
        <td><%= skillset.tool.name if skillset.tool %></td>
        <td><%= skillset.proficiency if skillset.proficiency %></td>
        <td><%= link_to 'Show', skillset %></td>
        <td><%= link_to 'Edit', edit_skillset_path(skillset) %></td>
        <td><%= link_to 'Destroy', skillset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Skillset', new_skillset_path %>
<%= link_to 'New Staff', new_staff_path %>
<%= link_to 'New Tool', new_tool_path %>

app/views/skillsets/new.html.erb
<h1>New Skillset</h1>

<%= render 'form' %>

<%= link_to 'Back', skillsets_path %>

app/views/skillsets/show.html.erb
<p>
  <strong>Staff:</strong>
  <%= @skillset.staff.name_full %>
</p>

<p>
  <strong>Tool:</strong>
  <%= @skillset.tool.name %>
</p>

<p>
  <strong>Proficiency:</strong>
  <%= @skillset.proficiency %>
</p>

<%= link_to 'Edit', edit_skillset_path(@skillset) %> |
<%= link_to 'Back', skillsets_path %>