config/routes.rb
Rails.application.routes.draw do
  resources :departments
  resources :offices
  resources :offices
  resources :offices
  devise_for :staffs

  resources :projects
  resources :offices
  resources :skillsets
  resources :tools
  resources :staffs

  authenticated :user do
    root 'skillsets#index', as: :authenticated_root
  end
  root 'welcome#index'

end

app/views/layouts/_header.html.erb
<nav class='navbar navbar-default'>
  <div class='container-fluid'>
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#bs-example-navbar-collapse-1' aria-expanded='false'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
			<%= link_to 'Home', root_path, class: 'navbar-brand' %>
		</div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class='collapse navbar-collapse' id='bs-example-navbar-collapse-1'>
      <ul class='nav navbar-nav'>
      	<li><%= link_to 'Staff', staffs_path %></li>
        <li><%= link_to 'Offices', offices_path %></li>
      	<li><%= link_to 'Tools', tools_path %></li>
      	<li><%= link_to 'Skillsets', skillsets_path %></li>
        <li><%= link_to 'Projects', projects_path %></li>
        <li><%= link_to 'Departments', departments_path %></li>
      </ul>

      <ul class='nav navbar-nav navbar-right'>
        <% if staff_signed_in? %>
          <li class='navbar-text'>Hi <%= current_staff.name_first %>! Not you?</li>
          <li><%= link_to 'Edit profile', edit_staff_registration_path %></li>
          <li><%= link_to 'Sign out', destroy_staff_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to 'Sign up', new_staff_registration_path %></li>
          <li><%= link_to 'Sign in', new_staff_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Expertise</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

	<div class='container'>

		<% flash.each do |name, msg| %>
		  <%= content_tag :div, msg, class: 'alert alert-info' %>
		<% end %>

		<%= yield %>

	</div>

</body>
</html>